# Generated by Django 5.2.3 on 2025-07-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст вопроса', verbose_name='Текст вопроса')),
                ('difficulty', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], help_text='Выберите уровень сложности', max_length=10, verbose_name='Уровень сложности')),
                ('question_type', models.CharField(choices=[('open', 'Open-ended'), ('choice', 'Multiple Choice')], help_text='Выберите тип вопроса', max_length=10, verbose_name='Тип вопроса')),
                ('correct_answer', models.TextField(blank=True, help_text='Введите правильный ответ', verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, help_text='Введите объяснение ответа', verbose_name='Объяснение')),
                ('category', models.ForeignKey(help_text='Выберите категорию вопроса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
            ],
        ),
    ]
