# Generated by Django 5.2.3 on 2025-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='detailed_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Детальный анализ ответа по критериям'),
        ),
    ]
