# Generated by Django 5.2.3 on 2025-08-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_answer_detailed_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='expert_answer',
        ),
        migrations.DeleteModel(
            name='ExpertAnswer',
        ),
    ]
